variable "env" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr" {}
variable "default_vpc_id" {}
variable "default_rt_ID" {}
variable "default_vpc_cidr_block" {}
variable "frontend_subnets" {}
variable "backend_subnets" {}
variable "db_subnets" {}
variable "Availability_zones" {}
